### ISSUE TITLE
Unlist stories using the author's page

### ISSUE THREAD

**Issue by ReallyNotAHat** [RogerDodger/WriteOff#5]
Unless it's not obvious, I'm kinda just throwing whatever I think the site could use up on here. :P Hopefully this is useful to you; if not, ignore it. 

But yeah, it's not currently obvious how to remove stories, since you have to do so on the submissions page for the contest, but most people won't think to look there since it's closed during the contest. I'd suggest adding the post/remove checkboxes that are there to the list of stories that pop up if you click on your alias names in the alias dropdown.

**Comment by RogerDodger** [comment]
(It's incredibly useful. When I actually get around to doing stuff these will be the first things I get to.)

**Comment by RogerDodger** [comment]
Resolving this to wontfix. I think it's preferred if there isn't an easy way to unilaterally remove everything you've submitted.

The main reason for someone to unpublish something should be because they're trying to get that specific thing published elsewhere, and for that purpose the current UI works well.

I'm not a fan of the (sadly more typical), "I want to scrub everything because I'm embarrassed about it / having a breakdown," usage, which this would enable. That functionality is still there. I just don't want it encouraged.
