### ISSUE TITLE
Visualise guesses in a cleaner way

### ISSUE THREAD

**Issue by RogerDodger** [RogerDodger/WriteOff#9]
There are as I see it two primary use-cases for the guess data:

- Artists want to see how well people are guessing their stories
- Participants in general want to see what stories were easiest to guess, and who guessed them

As it stands, the data is just shown as a huge table, and it's very ugly.

On top of that, the first use case is not being met well. Artists who receive more guesses against them are also more likely to have correct guesses made against them. The best example of this is Cold_in_Gardez, who receives more guesses than any other artist. Even though there's always some people that guess which he wrote, there are also many more that guess him for other stories too. 

The visualisation should show how well the author avoided (or failed to avoid) detection, with consideration for how many people were looking for him/her.

**Comment by ReallyNotAHat** [comment]
So, a while ago I googled 'high-dimensional data visualization' to see if anyone had a good way to do this. 

I didn't come up with anything that fit really well, but I did find an interesting one called an 'arc diagram'. Here's an example: http://deliveryimages.acm.org/10.1145/1750000/1743567/figs/f5b.jpg

I think that something this, but with two columns and the pipes running from one to the other, might work well for an 'overview' type of graphic. guessers on one side and stories on the other. Give correct guesses and incorrect guesses different colors, and maybe put a node that expresses the ratio of incorrect/correct guesses as mixture of colors, and it should give a readable overview that only scales in one direction. Stories with lots of lines leading to them were guessed a lot, and people with lots of lines leading from them made lots of guesses. The average color of all the lines would give an indication of how well they guessed/were guessed. 

The downside to this is that, while it gives a nice overview, it's rather more difficult to get specific information from. Following each line would be tedious... although tooltips might work? I dunno. If the plot was arranged so that the lines were clearly distinguishable, someone could hover over each one to get who the guesser/story was. This might have its own scalability problems, though. 

A collapsible thing under each name/story with specific listings might work, but that's not particularly elegant. 

Hopefully this sparks some thoughts for you. This thing has kinda strange requirements, if we want both a good overview and also specific information available at once.

**Comment by RogerDodger** [comment]
Wow that sounds perfect actually.

**Comment by RogerDodger** [comment]
Oh even better:

The graph has three columns in it. The first column is guessers, the second is artists, and third is entries. The guess lines pass through the respective vertex to show the guesser, guessed, and entry.

**Comment by ReallyNotAHat** [comment]
I like the three-column idea. And since the guessers and the guessed columns have the same names anyways, might as make the 'guessed' column simply nodes that line up with the guessers so you don't need to add a bunch more text. If you moved the story names up against the finals/prelims column, You could almost display the guesses information in the space we're currently using by just adding the pipes.

Actually, could you make it a collapsible column? Put a shrunk column containing the guessed nodes and pipes between the author/story names. Clicking it would vanish the finals/prelims column and expand the pipes/nodes, sliding the story names over for easy viewing.

**Comment by RogerDodger** [comment]
I've got a working implementation live on the website now. With the curved lines the visualisation makes the intricacies *much* clearer. I'm pretty happy with it.

I'm a little concerned for performance reasons that the paint is too complex. The biggest graph on record is https://writeoff.me/event/36-I-Regret-Nothing/fic/results and it's drawing something like a thousand lines. That's probably not too bad, but if for example phones can't handle it I'll have to add a button or something.
